// <auto-generated />
using System;
using API_PROYECTO_APLICADO.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_PROYECTO_APLICADO.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Models.Admisiones", b =>
                {
                    b.Property<int>("AdmisioneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdmisioneId"));

                    b.Property<byte[]>("ActaNacimiento")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("CertificadoBachiller")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("CertificadoMedico")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CiudadNacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoAdmicionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Fotografia")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("LugarNacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RecordNotas")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Tarjetavacunacion")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoCasa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdmisioneId");

                    b.ToTable("Admisiones");
                });

            modelBuilder.Entity("Shared.Models.Asignaturas", b =>
                {
                    b.Property<int>("AsignaturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsignaturaId"));

                    b.Property<int>("CantidadEstudiantes")
                        .HasColumnType("int");

                    b.Property<string>("CodigoMateria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<bool>("EsLaboratorio")
                        .HasColumnType("bit");

                    b.Property<string>("NombreMateria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrecioCredito")
                        .HasColumnType("float");

                    b.Property<string>("Seccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("AsignaturaId");

                    b.ToTable("Asignaturas");
                });

            modelBuilder.Entity("Shared.Models.Carreras", b =>
                {
                    b.Property<int>("CarreraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarreraId"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarreraId");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("Shared.Models.DetalleAsignaturas", b =>
                {
                    b.Property<int>("DetalleAsignaturaId")
                        .HasColumnType("int");

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("int");

                    b.Property<string>("Aula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiaId")
                        .HasColumnType("int");

                    b.Property<string>("Edificio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("DetalleAsignaturaId");

                    b.ToTable("DetalleAsignaturas");
                });

            modelBuilder.Entity("Shared.Models.DetalleSeleccionAsignatura", b =>
                {
                    b.Property<int>("DetalleSeleccionAsignaturaId")
                        .HasColumnType("int");

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("int");

                    b.Property<int>("CantidadCreditos")
                        .HasColumnType("int");

                    b.Property<int>("SeleccionAsignaturaId")
                        .HasColumnType("int");

                    b.HasKey("DetalleSeleccionAsignaturaId");

                    b.ToTable("DetalleSeleccionAsignatura");
                });

            modelBuilder.Entity("Shared.Models.Dias", b =>
                {
                    b.Property<int>("DiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiaId"));

                    b.Property<string>("NombreDia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiaId");

                    b.ToTable("Dias");

                    b.HasData(
                        new
                        {
                            DiaId = 1,
                            NombreDia = "Lunes"
                        },
                        new
                        {
                            DiaId = 2,
                            NombreDia = "Martes"
                        },
                        new
                        {
                            DiaId = 3,
                            NombreDia = "Miercoles"
                        },
                        new
                        {
                            DiaId = 4,
                            NombreDia = "Jueves"
                        },
                        new
                        {
                            DiaId = 5,
                            NombreDia = "Viernes"
                        },
                        new
                        {
                            DiaId = 6,
                            NombreDia = "Sabado"
                        },
                        new
                        {
                            DiaId = 7,
                            NombreDia = "Domingo"
                        });
                });

            modelBuilder.Entity("Shared.Models.EstadosAdmision", b =>
                {
                    b.Property<int>("EstadoAdmisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoAdmisionId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstadoAdmisionId");

                    b.ToTable("EstadosAdmision");

                    b.HasData(
                        new
                        {
                            EstadoAdmisionId = 1,
                            Descripcion = "Pendiente"
                        },
                        new
                        {
                            EstadoAdmisionId = 2,
                            Descripcion = "Aceptado"
                        },
                        new
                        {
                            EstadoAdmisionId = 3,
                            Descripcion = "Rechazado"
                        });
                });

            modelBuilder.Entity("Shared.Models.Facturaciones", b =>
                {
                    b.Property<int>("FacturacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacturacionId"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Monto")
                        .HasColumnType("float");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SemestreId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("FacturacionId");

                    b.ToTable("Facturaciones");
                });

            modelBuilder.Entity("Shared.Models.Reservaciones", b =>
                {
                    b.Property<int>("ReservacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservacionId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoReservacioneId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ReservacionId");

                    b.ToTable("Reservaciones");
                });

            modelBuilder.Entity("Shared.Models.Roles", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("RolName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            RolName = "Admin"
                        },
                        new
                        {
                            RolId = 2,
                            RolName = "Estudiante"
                        },
                        new
                        {
                            RolId = 3,
                            RolName = "Profesor"
                        },
                        new
                        {
                            RolId = 4,
                            RolName = "Admisor"
                        });
                });

            modelBuilder.Entity("Shared.Models.SeleccionAsignaturas", b =>
                {
                    b.Property<int>("SeleccionAsignaturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeleccionAsignaturaId"));

                    b.Property<int>("CantidadAsignaturasSeleccionadas")
                        .HasColumnType("int");

                    b.Property<int>("CantidadCreditosPermitidos")
                        .HasColumnType("int");

                    b.Property<int>("CantidadCreditosSeleccionados")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaSeleccion")
                        .HasColumnType("datetime2");

                    b.Property<int>("SemestreId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("SeleccionAsignaturaId");

                    b.ToTable("SeleccionAsignaturas");
                });

            modelBuilder.Entity("Shared.Models.Semestres", b =>
                {
                    b.Property<int>("SemestreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemestreId"));

                    b.Property<double>("CargoInscripcion")
                        .HasColumnType("float");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinSeleccion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicioSeleccion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SemestreId");

                    b.ToTable("Semestres");
                });

            modelBuilder.Entity("Shared.Models.TiposReservaciones", b =>
                {
                    b.Property<int>("TipoReservacioneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoReservacioneId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoReservacioneId");

                    b.ToTable("TiposReservaciones");

                    b.HasData(
                        new
                        {
                            TipoReservacioneId = 1,
                            Descripcion = "Laboratorio"
                        },
                        new
                        {
                            TipoReservacioneId = 2,
                            Descripcion = "Proyector"
                        });
                });

            modelBuilder.Entity("Shared.Models.Usuarios", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<int>("AdmisionId")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronicoInstitucional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronicoPersonal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaEgreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("FotoUsuario")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Matricula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoCasa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Shared.Models.DetalleAsignaturas", b =>
                {
                    b.HasOne("Shared.Models.Asignaturas", null)
                        .WithMany("DetalleAsignaturas")
                        .HasForeignKey("DetalleAsignaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.DetalleSeleccionAsignatura", b =>
                {
                    b.HasOne("Shared.Models.SeleccionAsignaturas", null)
                        .WithMany("DetalleSeleccionAsignaturas")
                        .HasForeignKey("DetalleSeleccionAsignaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.Asignaturas", b =>
                {
                    b.Navigation("DetalleAsignaturas");
                });

            modelBuilder.Entity("Shared.Models.SeleccionAsignaturas", b =>
                {
                    b.Navigation("DetalleSeleccionAsignaturas");
                });
#pragma warning restore 612, 618
        }
    }
}
